### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by doggo-rules** [monkoose/fzf-hoogle.vim#15]
I installed Hoogle today and using it from the command line and with server works but no results show up when using through fzf hoogle.

My config:
```vim
call plug#begin()
  Plug 'monkoose/fzf-hoogle.vim'
  Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'}
call plug#end()

let g:hoogle_path='/usr/bin/hoogle'
```

**Comment by doggo-rules** [comment]
jq-1.6
nvim 0.4.3
Hoogle 5.0.17.3

**Comment by monkoose** [comment]
Hello. 
Does it show anything? Errors or something?
Try `hoogle --json --count=10 map` in your shell, do you get any results?
If so try to change `g:hoogle_fzf_cache_file` or make sure  it presents in your system. It should be in `your vim-plug plugins directory/fzf-hoogle.vim/hoogle_cache.json`.
Maybe update your hoogle because 5.0.17.3 is outdated, and make sure you have `awk`.

**Comment by doggo-rules** [comment]
Hey, I don't remember how I fixed the issue. Forgot I had this open here. Closing it.
