### ISSUE TITLE
`i` inserted in search field after pressing enter

### ISSUE THREAD

**Issue by sandersantema** [monkoose/fzf-hoogle.vim#6]
Every time I press enter an `i` gets inserted. I'm using the latest neovim git version together with the latest fzf and fzf-vim.

Before pressing enter:
![image](https://user-images.githubusercontent.com/21057514/91858944-246c7e80-ec6a-11ea-84e3-0720ab1c2599.png)

After pressing enter:
![image](https://user-images.githubusercontent.com/21057514/91858975-2cc4b980-ec6a-11ea-8df4-ab507593fd5f.png)

This happens regardless of what is typed in the search field before hand.

**Comment by monkoose** [comment]
Hello, thank you for this issue.
The plugin uses some hack for fzf window, that can't start terminal buffer on neovim in insert mode if it was invoked from the previous fzf window https://github.com/monkoose/fzf-hoogle.vim/blob/master/autoload/hoogle.vim#L79 
So with this hack it on every `Enter` hit just imitates user's `i` hit too.

I will investigate this, the problem that I use custom fzf and stable neovim release. But seems like it has been fixed in neovim 0.5 or fzf itself.
Will fix this on weekends or start of the next week.

**Edit:** Tested with neovim nightly release and have the same behavior as you. So seems like neovim devs fixed issue with starting neovim terminal buffer in insert mode from previous terminal buffer. Will fix it on weekends.

**Comment by monkoose** [comment]
Fixed 4216645e9284f2fa192795cc2d1e4cc640b5dc47
