### ISSUE TITLE
Example text is hard to read in fzf preview window using Nord color scheme

### ISSUE THREAD

**Issue by sandersantema** [monkoose/fzf-hoogle.vim#7]
The example text has a muted grey color using the Nord color scheme, however to me it doesn't seem very readable on the given screen shot either.

Nord:
![image](https://user-images.githubusercontent.com/21057514/91859139-5e3d8500-ec6a-11ea-8395-f3a5f2e8990b.png)

Screenshot:
![image](https://user-images.githubusercontent.com/21057514/91859426-bb393b00-ec6a-11ea-9ee2-234513b2a3d8.png)

Perhaps a less muted color should be used or an option given to customize the preview?

**Comment by monkoose** [comment]
Hello again.

It uses your terminal colorscheme's gray color (color8 in 256 colors), so that means that your terminal colorscheme produce such bad contrast (if you use nord colorscheme in your terminal too for sure).
Sorry, but I'm not willing to make every possible color configurable for such plugin (at least for now, i will leave this issue open and if there would be more users with identical issue i will fix it).
So there are two options you can change color8 of your terminal colorscheme to have better contrast, or you can fork and change `tput setaf 8` in this line https://github.com/monkoose/fzf-hoogle.vim/blob/master/bin/preview.sh#L21 to any number between 0 and 255, you can try `6` first for example.

**Comment by resolritter** [comment]
They're also unreadable for me, but the suggestion to change `tput`'s parameters worked.

@monkoose How about setting that number through an environment variable with a default fallback? Then people wanting to change the colors won't have to fork it, just change the variable

```bash
if ! [ "$FZF_HOOGLE_CODE_COLOR" ]; then FZF_HOOGLE_CODE_COLOR = 8; fi

$(tput setaf $FZF_HOOGLE_CODE_COLOR)
```

while we're at it, the same could be done for all the other `tput` calls as well : - )

**Comment by monkoose** [comment]
It's only one color, but there are other too. And not only in `preview.sh` but in vim script too like https://github.com/monkoose/fzf-hoogle.vim/blob/master/autoload/hoogle.vim#L62 with different format, that will just confuse users. And if you use different color schemes for terminal and vim it can happen that all of this colors would be unreadable.

Ok i will think about adding variables for this colors, but for me personally I think the same color scheme for vim and terminal is better. 

@resolritter
Which color schemes are you using?

**Comment by resolritter** [comment]
I am using one color scheme for the Kitty terminal. The theme definition is done through the configuration file, as an example here:

https://github.com/dexpota/kitty-themes/blob/master/themes/AdventureTime.conf

And many more themes at: https://github.com/dexpota/kitty-themes/blob/master/README.md

It just happened that, in my specific configuration, the color 8 (you're using `tput setaf 8`, so that's what gets assigned) was set to a grey tone which was sort of unreadable. I've changed this configuration, so this is no longer an issue for me.

**Comment by monkoose** [comment]
Guys, what do you think about making code examples color just different by default without adding new variables? I still think that a lot of variables for such plugin is just overkill.

I'm thinking about cyan color (`tput setaf 6`) of the terminal color scheme.

**Comment by resolritter** [comment]
Having variables provides the most flexibility since they're configurable directly by the end user. While they'd add a bit more complexity to the plugin's _**maintainability**_ (not usage), in terms of configuration purpose they're not "overkill"... I'd say they're the most straightforward solution to this.

> I'm thinking about cyan color (`tput setaf 6`) of the terminal color scheme.

Changing the default is fine IMO.
